### PR TITLE
Hex bug fix

### PR DESCRIPTION
**Pull request by harisang**
This PR fixes some minor bug introduced in PR #31 with the conversion of Hex Bytes to strings and vice versa.

### CODE REVIEW

**Review by bram-vdberg — APPROVED** [review]
Do we need to apply this change to the whole project? I see we use the `.hex()` method in a few other files as well.

**Comment by shubhagarwal03** [comment]
I'll check to see if its needed in other files, but I believe the rest of the codebase is as is, and had no issues in the prev deployment.

**Comment by fhenneke** [comment]
There is one conversion to `to_0x_hex` missing in the `get_order_data` function.

Some of the other uses are for use in other methods of the package. Some of the should handle strings without `0x` prefix correctly. But probably worth double checking.

**Comment by harisang** [comment]
Yeah good catch, must pushed the fix for the `get_order_data()` function. Getting rate limited again so will wait to test it locally before merging.

**Pull request merged**
